language: python
python:
- '2.7'

before_install:
   - mkdir -p build/html
   - mkdir source/_static
   - wget http://jaist.dl.sourceforge.jp/vlgothic/62375/VLGothic-20141206.zip
   - unzip VLGothic-20141206.zip
   - cd VLGothic
   - sudo cp *.ttf /usr/share/fonts/
   - fc-cache
   - cd ..

install: pip install -q -r requirements.txt

script: 
   - make html
   - ls -l build/html

notifications:
    slack: h-itg-dev:4z5R67svHYtxSBd3o6dsZHrT
    webhooks:
      urls:
        - http://52.68.213.92:8080/webhook
      on_failure: never # default: always

