language: python
python:
- '2.7'
install: pip install -q -r requirements.txt
script: make html

notifications:
    slack: h-itg-dev:4z5R67svHYtxSBd3o6dsZHrT
    webhooks:
      urls:
        - http://13.114.123.10:8080/webhook
      on_failure: never # default: always

